import pandas as pd
import unidecode

# Lista manual de nomes comuns
nomes_masculinos = [
    "ADÃO", "ADEMAR", "ADEMILSON", "ADRIANO", "ALAN", "ALCIDES", "ALESSANDRO", "ALEX", "ALEXANDRE", "ALEXANDRO",
    "ALEXSANDRO", "ALISSON", "ALLETO", "ALVARO", "ALYSSON", "AMILTON", "ANDERSON", "ANDRE", "ANDRÉ", "ANTONIO",
    "ANTÔNIO", "AQUILES", "ARIEL", "ARTHUR", "ARTUR", "AUGUSTO", "BERNARDO", "BRENO", "BRUNO", "CALEBE", "CARLOS",
    "CAUAN", "CELSO", "CHARLES", "CHRISTIAN", "CHRYSTOPHER", "CÍCERO", "CLAUDINEI", "CLAUDINIR", "CLAUDIO", "CLÁUDIO",
    "CLÉO", "CLEYDSON", "CLOVIS", "CRISTIANO", "DAÊNIO", "DALTON", "DANIEL", "DANILO", "DARLAN", "DAVI", "DAVID",
    "DAVIH", "DÉCIO", "DENIS", "DHANIEL", "DIANO", "DIEGO", "DILCEU", "DIOGO", "DIONE", "DIOUNATAN", "DOMINGOS",
    "DOUGLAS", "EDEGAR", "EDERSON", "EDGAR", "EDI", "EDSON", "EDUARDO", "ELCIO", "ELDER", "ELENO", "ELIAS", "ELMAR",
    "ELVIS", "EMERSON", "ESDRAS", "EVANDRO", "EVANILSON", "EVERTON", "EZEQUIEL", "FABIANO", "FABIO", "FÁBIO",
    "FABRÍCIO", "FELIPE", "FÉLIX", "FELLIPE", "FERNANDO", "FILLIPE", "FLÁVIO", "FRANCISCO", "FREITAS", "GABRIEL",
    "GEISON", "GERALDO", "GERSON", "GESSÉ", "GEZUEL", "GIAN", "GIDEÃO", "GILBERTO", "GILMAR", "GIMENI", "GIOVANNI",
    "GLEISON", "GREGORY", "GREGRI", "GUILHERME", "GUSTAVO", "HEBER", "HEITOR", "HELADIO", "HÉLIO", "HELON", "HEMERSON",
    "HENRIKE", "HENRIQUE", "HERIAN", "HIAGO", "HILTOM", "HOMERO", "IGOR", "ISAAC", "ISAQUE", "ISMAEL", "ISRAEL", "ÍTALI",
    "ÍTALO", "IVAN", "JACIR", "JACKSON", "JACSON", "JADIR", "JAIME", "JAIR", "JAIRO", "JARDEL", "JAUMIR", "JEAN",
    "JEANDRO", "JEFERSON", "JEFFERSON", "JHONATA", "JHONATTAN", "JOAO", "JOÃO", "JOCELITO", "JOE", "JOEFINE", "JOEL",
    "JOHNKIN", "JONAS", "JONATAN", "JONATAS", "JORGE", "JOSE", "JOSÉ", "JOSEFO", "JOSOÉ", "JOSUÉ", "JUAREZ", "JULIANO",
    "JULIO", "JÚLIO", "JUNIOR", "KAIQUE", "KALEL", "KAUÃ", "KAUAN", "KAUE", "KEVIN", "KRIS", "LAERTE", "LAGARONE",
    "LEANDRO", "LEONARDO", "LEONIR", "LUCAS", "LUCCA", "LUCIANO", "LUIS", "LUIZ", "LUÍZ", "MÁCIO", "MAICON", "MANUEL",
    "MARCELO", "MARCIO", "MÁRCIO", "MARCO", "MARCOS", "MARCUS", "MARIO", "MARLON", "MARNON", "MATHEUS", "MAURÍCIO",
    "MAURO", "MESSALAS", "MICAEL", "MIGUEL", "MILTON", "MIZAEL", "NAILTON", "NATALÍCIO", "NELSON", "NICHOLAS", "NICKSON",
    "NICOLÁS", "NILTON", "NIOMAR", "ODAIR", "ORLANDO", "OSVALDO", "OTÁVIO", "OTONIEL", "PABLO", "PATRICK", "PATRIK",
    "PATRYCK", "PAULO", "PEDRO", "PR.", "RAFAEL", "RAIMUNDO", "RAMON", "RAY", "REGINALDO", "RENAN", "RENATO", "RICARDO",
    "ROBERTO", "ROBSON", "RODERVAL", "RODINEI", "RODNEY", "RODRIGO", "ROGER", "ROGERIO", "ROGÉRIO", "ROGINEI", "RONALDO",
    "RUBENILSON", "RUDINEI", "RUDY", "RUI", "SAMUEL", "SANDRO", "SAULO", "SÉRGIO", "SÉRIO", "SIDINEI", "SÓCRATES",
    "TASSO", "TELLES", "THAWAN", "THIAGO", "THOMAS", "TIAGO", "UILIAM", "VAGNELSON", "VALDECI", "VALDECIR", "VALDEMAR",
    "VALDIR", "VALMIR", "VANDERLEI", "VICTOR", "VINICIUS", "VINICÍUS", "VINÍCIUS", "VITOR", "WASHINGTON", "WAYNER",
    "WELINTON", "WELITON", "WELLINGTON", "WELLINTON", "WERNER", "WESLEI", "WESLEY", "WILLIAM", "WILLIAN", "WILSON"
]
nomes_femininos = [
    "ADRIANA", "ADRIANE", "ADRIELE", "ADRIELI", "AGATHA", "ALANA", "ALDÊNIA", "ALESSANDRA",
    "ALEXANDRA", "ALICE", "ALINE", "ALINY", "ALLINE", "ALVINA", "ALYNE", "AMABILY", "AMANDA",
    "AMARILDA", "ANA", "ANDREA", "ANDREIA", "ANDRÉIA", "ANDRESA", "ANDRESSA", "ANDRIÊ",
    "ANDRIELE", "ANELISE", "ANESIA", "ANGELICA", "ANGÉLICA", "ANNA", "ANTONELLA", "ANTONIA",
    "APARECIDA", "ARIANE", "ARLETE", "AURORA", "AUTA", "BARBARA", "BÁRBARA", "BEATRIZ",
    "BERENICE", "BETANIA", "BIANCA", "BRENDA", "BRIGIDA", "BRUNA", "CAMILA", "CAMILLA",
    "CAREN", "CARINE", "CARLA", "CARLISE", "CARMEM", "CARMEN", "CAROLINA", "CAROLINE",
    "CASSIA", "CÁSSIA", "CATARINA", "CATHARINA", "CATIA", "CÁTIA", "CATIELI", "CELEIDE",
    "CELIA", "CHAIANA", "CHAIANE", "CHRISTIANE", "CHRYSTIANE", "CICERA", "CILENE", "CINARA",
    "CLARA", "CLARI", "CLARICE", "CLAUDETE", "CLAUDIA", "CLÁUDIA", "CLAUDIANE", "CLECIA",
    "CLEICE", "CLEIDECIANIA", "CLEONICE", "CLEUSA", "CLOTILDE", "CRISSIANE", "CRISTIANE",
    "CRISTINA", "DAIANE", "DAIANI", "DAIANNY", "DALILA", "DAMARIS", "DANIELA", "DANIELE",
    "DANIELLE", "DANIELLY", "DANÚBIA", "DANUSA", "DAYANE", "DAYSE", "DEBORA", "DÉBORA",
    "DEISE", "DENICE", "DENISE", "DENIZIA", "DEOCELIA", "DIANA", "DIANE", "DIELE", "DIRCÉIA",
    "DIULHANE", "DJENIFER", "DORISMAR", "DRIELLY", "DULCE", "EDIAMARA", "EDINEIA", "EDNA",
    "EDUARDA", "ELAINE", "ELANE", "ELIANE", "ELIENE", "ELISABETE", "ELISABETH", "ELISAETE",
    "ELISAMA", "ELISANGELA", "ELISIA", "ELIZABETE", "ELIZANDRA", "ELIZIANE", "ELLIS",
    "EMANUELA", "EMANUELI", "EMANUELLE", "EMELI", "EMILY", "ENI", "ÉRICA", "ERIKA", "ERONILDES",
    "ESTER", "EUNICE", "EVA", "EVANICE", "EVILYN", "FABIANA", "FABIOLA", "FABÍOLA", "FABIULA",
    "FABRÍCIA", "FÁTIMA", "FAYGA", "FERNANDA", "FLÁVIA", "FLAVIANA", "FLORA", "FRANCIELE",
    "FRANCIELI", "FRANCIELLA", "FRANCIELLE", "FRANCINE", "FRANCINY", "GABRIELA", "GABRIELE",
    "GABRIELLE", "GABRIELLI", "GEISIELE", "GENI", "GENILMA", "GEOVANA", "GEOVANNA", "GILSAINE",
    "GILVANA", "GIOVANA", "GIOVANE", "GIOVANNA", "GISEAINE", "GISELE", "GLAUCIENE", "GLEICE",
    "GLEIZA", "GRAÇA", "GRACIA", "GRACIANE", "GRACIETE", "GRAZIELE", "GRAZIELLA", "GREICE",
    "HAISLA", "HANNA", "HAYDRIME", "HEIDE", "HELEN", "HELENA", "HELLEN", "HELOISA", "HEYLIN",
    "HORACILIA", "IASCRA", "IASMIN", "ILIANA", "INGRID", "IRACI", "IRINÉIA", "ISABEL", "ISABELE",
    "ISABELLA", "ISABELLY", "ISADORA", "ISIS", "IVA", "IVANI", "IVONE", "IVONETE", "IZABELA",
    "IZABELLY", "IZADORA", "JACE", "JAKELINE", "JAMILE", "JANAINA", "JANAÍNA", "JANAYNA",
    "JANETE", "JANICE", "JANISIA", "JAQUELINE", "JASMIN", "JAYANE", "JEANNE", "JEISIANE",
    "JEMIMA", "JENIFER", "JENNIFER", "JERUSA", "JESNE", "JESSICA", "JÉSSICA", "JHENIFER",
    "JOANA", "JOELMA", "JOSEANE", "JOSEFINA", "JOSIANE", "JOSIANI", "JOSIELMA", "JOSILENE",
    "JOVANA", "JOYCE", "JOZENI", "JUCELI", "JUCICLEIDE", "JULIA", "JÚLIA", "JULIANA",
    "JULIANE", "JULIETA", "JUSCÉLIA", "KALIANE", "KAMILA", "KAMILLE", "KAREN", "KARINA",
    "KARINE", "KARLA", "KAROLINE", "KARYNE", "KATE", "KATHELEEN", "KATIA", "KATIUSIRA",
    "KATRINE", "KATÚCIA", "KÉDIMA", "KEICIANE", "KEILA", "KEILLY", "KEITHENE", "KELLY",
    "KENZA", "KESIA", "KESSIA", "KESSILER", "KETHELY", "KETLEIN", "KETLYN", "KETTY", "KRISCIA",
    "LAIANE", "LAILA", "LAÍS", "LAISA", "LANA", "LARA", "LARISSA", "LAUANE", "LAURA",
    "LAUREANE", "LAURECI", "LEANDRA", "LÊDA", "LEILA", "LENI", "LETICIA", "LETÍCIA", "LIANA",
    "LIDIA", "LILIAN", "LINA", "LIS", "LISALI", "LISIANE", "LIVIA", "LORINI", "LOURDES",
    "LUANA", "LUANY", "LUARA", "LUBIANA", "LÚCIA", "LUCIANA", "LUCIANE", "LUCICLAUDIA",
    "LUCIELA", "LUDIMILA", "LUDMILA", "LUIGI", "LUISA", "LUIZA", "LUZIA", "MADALENA",
    "MAIARA", "MÁIRA", "MALU", "MARA", "MARCELA", "MARCIA", "MÁRCIA", "MARI", "MARIA",
    "MARIANA", "MARIARA", "MARILENE", "MARINALVA", "MARINE", "MARINEIDE", "MARISA",
    "MARISETE", "MARIVANIA", "MARLEI", "MARLENE", "MARLI", "MARLISE", "MARY", "MAURINA",
    "MAYARA", "MAYERA", "MAYNARA", "MELANY", "MERY", "MICHELE", "MICHELLE", "MICHELLI",
    "MILENA", "MILYANE", "MIRIAN", "MIRIANNE", "MITIELA", "MONICA", "MONIQUE", "MONIZE",
    "NAIANE", "NAIARA", "NALANDA", "NARA", "NATALIA", "NATÁLIA", "NATALIE", "NATASHA",
    "NATHALE", "NATHALIA", "NATHALIE", "NATHALLY", "NATHALY", "NATIELE", "NAZIDE",
    "NEICI", "NEIDE", "NEIVA", "NELIA", "NELMA", "NELSA", "NEUSA", "NEUSETE", "NEUZA",
    "NILNINE", "NINI", "NOEMI", "NÚBIA", "OCÉLIA", "ODETE", "OLIVIA", "ORIANA", "PALOMA",
    "PAMELA", "PAOLA", "PATRICIA", "PATRÍCIA", "PAULA", "PERCEVERANA", "PEROLA",
    "PHAMELA", "POLIANE", "POLYANA", "POLYANE", "PRA.", "PRISCILA", "PRISCILLA", "PRISCYLLA",
    "PRYCYLLA", "RADJA", "RAFAELA", "RAIANE", "RAQUEL", "REBECA", "REGINA", "REJANE",
    "RENATA", "RILIANE", "RITA", "ROBERTA", "ROSA", "ROSANA", "ROSANE", "ROSANGEL",
    "ROSANGELA", "ROSE", "ROSELI", "ROSELIS", "ROSEMERI", "ROSILENE", "ROSITA",
    "RUNETE", "RUTH", "SABRINA", "SABRINE", "SADRI", "SALETE", "SAMANTA", "SAMARA",
    "SANDRA", "SANDY", "SANIRA", "SARA", "SCHEILA", "SCHIRLEY", "SELI", "SELMA",
    "SHAIANE", "SHAMIRA", "SHEILA", "SHIRLEY", "SIBELE", "SILMARA", "SILVANA",
    "SILVIA", "SILVIANE", "SIMARA", "SIMONE", "SINARA", "SIRLENE", "SOLANGE",
    "SOPHIA", "STEFANI", "STEFANIE", "STEFANY", "STEPHANY", "STHEFANY", "SUELEN",
    "SUELI", "SULIENE", "SUZANA", "TAINARA", "TAIS", "TAISA", "TAISE", "TALITA",
    "TALITHA", "TAMARA", "TAMIRES", "TATIANA", "TATIANE", "TAYNÁ", "TELMA",
    "TEREZA", "TEREZINHA", "THAINE", "THAIS", "THAÍS", "THAMIRES", "THÁVYNE",
    "THAYNILCE", "THAYS", "THAYSE", "THUANE", "THUANY", "THYLARA", "TUANI",
    "UELEN", "ÚRSULA", "VALDIRENE", "VALERIA", "VALÉRIA", "VALESKA", "VALMIRA",
    "VANIA", "VANILZE", "VENESSA", "VERA", "VERONI", "VERONICA", "VERÔNICA",
    "VILMA", "VITORIA", "VITÓRIA", "VIVIANE", "WANESSA", "WILIANA", "YAMILE",
    "YASMIN", "YENIFER", "ZAIDA", "ZENAIDE", "ZENILDA", "ZERONI"]


# Função para determinar o gênero
def identificar_genero(nome):
    primeiro_nome = unidecode.unidecode(nome.split()[0].upper())  # Remove acentos e usa apenas o primeiro nome
    if primeiro_nome in nomes_masculinos:
        return "Masculino"
    elif primeiro_nome in nomes_femininos:
        return "Feminino"
    else:
        return "Indeterminado"


# Carregar o arquivo Excel
file_path = r"C:\Users\WilsonMartins\Downloads\nome_genero.xlsx"
# ajuste o caminho se necessário
df = pd.read_excel(file_path)

# Aplicar a função de gênero
df['Gênero'] = df['NOME'].apply(identificar_genero)

# Salvar o resultado em um novo arquivo
output_file = "nome_genero_classificado_v2.xlsx"
df.to_excel(output_file, index=False)

print(f"Classificação concluída. O arquivo com gêneros foi salvo como {output_file}.")
